name: CI

on: [ push, pull_request ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
    name: Tests on PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: bz2, mycrpt, openssl
          tools: composer

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: "~/.composer/cache"
          key: "php${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php${{ matrix.php-versions }}-composer-"

      - name: Install dependencies
        run: composer update && composer install

      - name: Run tests
        run: composer test

  phpstan:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer, mycrpt, openssl

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: "phpstan-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "phpstan-composer-"

      - name: Install dependencies
        run: composer update && composer install

      - name: Perform static analysis
        run: composer phpstan
